In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import os
import numpy as np
import cv2
data_dir='/content/drive/MyDrive/Data'
classes=os.listdir(data_dir)
img_width=128
img_height=128

In [ ]:
classes

['4', '3', '1', '2']

In [ ]:
def create_data(input_dir):
  X=[]
  Y=[]

  classes=os.listdir(input_dir)

  for c in classes:
    file_list=os.listdir(os.path.join(input_dir,c))
    for f in file_list:
      img=cv2.imread(os.path.join(os.path.join(input_dir,c),f),0)
      img=cv2.resize(img,(img_width,img_height),interpolation=cv2.INTER_AREA)
      img=img.reshape(-1)
      img=img/255.0
      X.append(img)
      Y.append(c)

  X=np.asarray(X).astype('uint8')
  Y=np.asarray(Y).astype('uint8')
  return X,Y

In [ ]:
X,Y=create_data(data_dir)

In [ ]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [ ]:
Y

array([4, 4, 4, 4, 3, 3, 3, 3, 1, 1, 1, 1, 2, 2, 2, 2], dtype=uint8)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [ ]:
X_train.shape

(12, 16384)

In [ ]:
Y_test

array([1, 2, 4, 1], dtype=uint8)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(X_train,Y_train)

GaussianNB()

In [ ]:
predicted=model.predict([X_test[1]])
print("Actual",Y_test[1])
print("Predicted",predicted[0])

Actual 2
Predicted 1


/usr/local/lib/python3.10/dist-packages/sklearn/naive_bayes.py:515: RuntimeWarning: divide by zero encountered in log
  n_ij = -0.5 * np.sum(np.log(2.0 * np.pi * self.var_[i, :]))
/usr/local/lib/python3.10/dist-packages/sklearn/naive_bayes.py:516: RuntimeWarning: invalid value encountered in divide
  n_ij -= 0.5 * np.sum(((X - self.theta_[i, :]) ** 2) / (self.var_[i, :]), 1)
